name: Publish
description: Publish the Docker package

inputs:
  tag:
    description: Release tag
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3.6.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/SpaceServerUniverse/ssv:latest
          ghcr.io/SpaceServerUniverse/ssv:${{ inputs.tag }}
