name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: 'Release tag'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish the Docker package
        uses: ./.github/actions/publish
        with:
          tag: ${{ inputs.tag }}
